### ISSUE TITLE
opendrift reader for norfjords160

### ISSUE THREAD

**Issue by AndersOpdal** [OpenDrift/OpenDrift.github.io#1]
I have been using opendriftreading files both the Nordic4km and NordKyst800 archive files from thredds.met.no. this has been working well. Now I am trying to used a test-archive for area A5 from Norfjords160, located at https://thredds.met.no/thredds/dodsC/romshindcast/NorFjords160/A5. Here, I encounter two problems. 
1. The archive consist of multimple nc-files, each covering a small time window. The reader can not handle this. 
2. When trying to read just a single file using the following command: 

reader_norfjords = reader_netCDF_CF_generic.Reader('https://thredds.met.no/thredds/dodsC/romshindcast/NorFjords160/A05/norfjords_160m_his.nc4_2020040101-2020040200')

I get the following message:
**********************************************************
14:45:45 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: https://thredds.met.no/thredds/dodsC/romshindcast/NorFjords160/A05/norfjords_160m_his.nc4_2020040101-2020040200
14:45:45 DEBUG   opendrift.readers.reader_netCDF_CF_generic: Finding coordinate variables.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\st10873\.conda\envs\opendrift\lib\site-packages\opendrift\readers\reader_netCDF_CF_generic.py", line 254, in __init__
    raise ValueError('No geospatial coordinates were detected, cannot geolocate dataset')
ValueError**: **No geospatial coordinates were detected, cannot geolocate dataset****
***********************************************************

Is there any convenient way to get around these two problems?

**Comment by knutfrode** [comment]
Duplicate
